# -*- coding: utf-8 -*-
"""0613404_homework4_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvb3s7n-5AnmLORGbq953uJzs7Y4KTVp
"""

def duration(n,c,r,face):
  duration=0
  value =0
  for i in range(1,n+1):
    discount =1
    for j in range(1,i+1):
      discount = discount/(1+r)
    duration=duration+i*discount*c
    value = value+discount*c
    if(i==n):
      value = value+discount*face
      duration=duration+(n)*discount*face
  duration =duration/value
  return duration

def modified_duration(ans1,r):
  return ans1/(1+r)

def change(ans2,m):
  return ans2*m*0.0001*100

n =int(input("請輸入期數"))
co =float(input("請輸入債息(%)"))
ro =float(input("請輸入利率(%)"))
face =float(input("請輸入face value"))
c=co/100*face
r=ro/100
ans1=duration(n,c,r,face)
print("Duration=",ans1)
ans2=modified_duration(ans1,r)
print("Modified duration=",ans2)
m =int(input("變動多少個basis point"))
ans3=change(ans2,m)
print("change",m,"basis point,the price change",ans3,"%")