# -*- coding: utf-8 -*-
"""0613404_homework3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FAWKxEV48dnknHsAGnV9n6S7_-PMTfy7
"""

import datetime 
import time
def function1(year, month, day,year2,month2,day2):
  interval =(year-year2)*12+(month-month2)
  return interval*30
def function2(year, month, day,year2,month2,day2):
  date1 = datetime.date(year, month, day)
  date2 = datetime.date(year2,month2,day2)
  interval =date2-date1
  day = interval.days
  if(day>0):
    return day
  else:
    print("wrong input")

import math
def dirty(rate,bond,w,day):
  n = day//180
  r= bond/100/2
  c =rate/2
  value=0
  for i in range(n+1):
    value=value+c*(math.pow((1+r),-(w+i)))
    if(i==n):
      value=value+(math.pow((1+r),-(w+i)))*100
  return value

method = int(input("which method to count conversion: actual/actual(1) or 30/360(2)"))
year = int(input("bond maturity year "))
month = int(input("bond maturity month "))
day =int(input("bond maturity day "))
year2 = int(input("settlement year "))
month2 = int(input("settlement month "))
day2 =int(input("settlement day "))
bond =float(input("bond yield (%) "))
rate = float(input("coupon rate(%) "))
if(method==1):
  day = function2(year,month,day,year2,month2,day2)
  w = (day%180)/180
  interest = rate*(1-(day%180)/180 )/2
  dirty_price = dirty(rate,bond,w,day)
  clean_price = dirty_price-float(interest)
  print("Dirty price",dirty_price)
  print("Clean price",clean_price)
if(method==2):
  day = function1(year,month,day,year2,month2,day2)
  w = (day%180)/180
  interest = rate*(1-(day%180)/180 )/2
  dirty_price = dirty(rate,bond,w,day)
  clean_price = dirty_price-float(interest)
  print("Dirty price",dirty_price)
  print("Clean price",clean_price)
else:
  print("wrong input")